In [245]:
import numpy as np 
np.__version__

'1.22.2'

In [246]:
np.arange(2,29,7)

array([ 2,  9, 16, 23])

In [247]:
np.linspace(2,9,5)

array([2.  , 3.75, 5.5 , 7.25, 9.  ])

In [248]:
np.random.random((3,3))

array([[0.57225191, 0.22308163, 0.95274901],
       [0.44712538, 0.84640867, 0.69947928],
       [0.29743695, 0.81379782, 0.39650574]])

In [249]:
np.random.normal(0,1,(3,3))

array([[0.20827498, 0.97663904, 0.3563664 ],
       [0.70657317, 0.01050002, 1.78587049],
       [0.12691209, 0.40198936, 1.8831507 ]])

In [250]:
np.random.randint(0,10,(3,3))

array([[9, 6, 5],
       [7, 8, 8],
       [9, 2, 8]])

COIN TOSS 1,0

In [251]:
a = []
for i in range(1,10):
    b = np.random.random_integers(0,1)
    a.append(b)
    i = i+1
print(a)

[0, 1, 1, 0, 1, 1, 1, 1, 1]


C:\Users\Fortune\AppData\Local\Temp\ipykernel_21088\2980037048.py:3: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead
  b = np.random.random_integers(0,1)


In [252]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [253]:
np.empty(2)

array([ 4.70691117e-005, -3.88157074e+282])

In [254]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))


In [255]:
print('x3 ndim: ', x3.ndim)
print('x3 shape: ', x3.shape)
print('x3 size: ', x3.size)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")
print("dtype:", x3.dtype)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
itemsize: 4 bytes
nbytes: 240 bytes
dtype: int32


In [256]:
x1[0]

5

In [257]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [258]:
x2[1,2]

8

In [259]:
x2[0,-1]

4

In [260]:
x2[-1,-1]

7

In [261]:
x1[0] = 3.14159

In [262]:
x1

array([3, 0, 3, 3, 7, 9])

In [263]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [264]:
x[:5]

array([0, 1, 2, 3, 4])

In [265]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [266]:
x2[:2,:2]

array([[3, 5],
       [7, 6]])

In [267]:
x2[:3, ::3]

array([[3, 4],
       [7, 8],
       [1, 7]])

In [268]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [269]:
x2[:,0]

array([3, 7, 1])

In [270]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [271]:
x.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [272]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [273]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [274]:
z = [99,4]
np.concatenate(([x,y,z]))

array([ 1,  2,  3,  3,  2,  1, 99,  4])

In [275]:
grid = np.array([[1,2,3],
                [4,5,6]])
grid.shape

(2, 3)

In [276]:
p = np.concatenate([grid, grid])
print(p)
print(p.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
(4, 3)


In [277]:
p = np.concatenate([grid, grid], axis=1)
print(p)
print(p.shape)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
(2, 6)


In [278]:
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [279]:
y = np.array([[99], 
                [99]])

y

array([[99],
       [99]])

In [280]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [281]:
x1,x2,x3 = np.split(x,[2,6])

In [282]:
print(x1,x2,x3)

[1 2] [3 4 5 6] [7 8 9]


In [283]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [284]:
upper, lower = np.vsplit(grid,[2])


In [285]:
print(upper, lower)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [286]:
left, right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [287]:
np.linspace(0,8,6).reshape(2,3)

array([[0. , 1.6, 3.2],
       [4.8, 6.4, 8. ]])

In [288]:
np.random.randint(0,10,(8,8))

array([[4, 3, 4, 4, 8, 4, 3, 7],
       [5, 5, 0, 1, 5, 9, 3, 0],
       [5, 0, 1, 2, 4, 2, 0, 3],
       [2, 0, 7, 5, 9, 0, 2, 7],
       [2, 9, 2, 3, 3, 2, 3, 4],
       [1, 2, 9, 1, 4, 6, 8, 2],
       [3, 0, 0, 6, 0, 6, 3, 3],
       [8, 8, 8, 2, 3, 2, 0, 8]])

In [289]:
x = np.arange(4)
print(x)
print(x+1)
print(x+2)
print(x/2)
print(x//2)

[0 1 2 3]
[1 2 3 4]
[2 3 4 5]
[0.  0.5 1.  1.5]
[0 0 1 1]


In [290]:
print(np.add(x,1))

[1 2 3 4]


In [292]:
x = np.random.randint(-5,3,(1,5))

In [293]:
np.absolute(x)

array([[3, 5, 1, 2, 1]])

In [294]:
np.abs(x)

array([[3, 5, 1, 2, 1]])

In [295]:
x = np.array([3-4j, 4-3j, 3 + 4j])

In [296]:
x 

array([3.-4.j, 4.-3.j, 3.+4.j])

In [298]:
np.absolute(x)

array([5., 5., 5.])

In [306]:
theta = np.linspace(0, np.pi, 3)

print('theta      = ', theta)
print('sin(theta) = ', np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("arctan(theta) = ", np.arctan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
arctan(theta) =  [0.         1.00388482 1.26262726]


In [307]:
from scipy import special

In [310]:
x = [1,5,10]
print(special.gamma(x))
print(special.gammaln(x))
print(special.beta(x,2))

[1.0000e+00 2.4000e+01 3.6288e+05]
[ 0.          3.17805383 12.80182748]
[0.5        0.03333333 0.00909091]


In [318]:
y = np.empty(5)
x = np.arange(5)
np.multiply(x,10, out= y)

array([ 0., 10., 20., 30., 40.])

In [324]:
a = np.arange(1,6)
print(x)
print(np.add.reduce(a))
print(np.multiply.reduce(a))
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

[0 1 2 3 4]
15
120
[ 0  1  3  6 10]
[0 0 0 0 0]


In [335]:
L = np.random.random(100)
sum(L)

50.47478376058294

In [342]:
bigL = np.random.rand(10000000)
%timeit sum(bigL)

1.74 s ± 221 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [343]:
bigL = np.random.rand(100000000)
%timeit np.sum(bigL)

172 ms ± 10.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [346]:
min(bigL), max(bigL)

(5.935602787054961e-09, 0.9999999957602168)

In [348]:
np.min(bigL), np.max(bigL)

(5.935602787054961e-09, 0.9999999957602168)

Numpy min,max,sum are way faster than python regular min,max,sum

In [351]:
bigL.max(), bigL.sum()  #Numpy shortcut

(0.9999999957602168, 50006876.771580234)

In [354]:
M = np.random.rand(3,4)
M

array([[0.30493334, 0.23163624, 0.10696951, 0.22071155],
       [0.96151281, 0.36573752, 0.13659648, 0.39288828],
       [0.63253051, 0.74535944, 0.08945538, 0.79125307]])

In [355]:
M.sum()

array([[0.82097016, 0.76255836, 0.50805658, 0.94794247],
       [0.28712858, 0.4977299 , 0.69741656, 0.31278831],
       [0.32095981, 0.49264183, 0.28808635, 0.41517413]])

In [358]:
np.percentile(bigL,25), np.percentile(bigL,50)

(0.2500410238113199, 0.5001090426443506)

In [359]:
a = np.array([0,1,2])
b = np.array([5,5,5])
a + b

array([5, 6, 7])

In [360]:
m = np.ones((3,3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [361]:
m+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [365]:
np.ones((3,2)) + np.ones((4,6))

ValueError: operands could not be broadcast together with shapes (3,2) (4,6) 

In [366]:
np.ones((3,4)) + np.ones(1)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [367]:
X = np.random.random((10,3))

In [368]:
Xmean = X.mean(0)
Xmean

array([0.54608025, 0.6067391 , 0.59729905])

In [369]:
X - Xmean

array([[ 0.33569516,  0.34131462,  0.32333615],
       [ 0.34987315,  0.12092075, -0.21252705],
       [-0.09536534, -0.28446328, -0.05637639],
       [ 0.45147091, -0.06598285, -0.17378996],
       [ 0.2129984 ,  0.17977477,  0.05780813],
       [-0.50273512,  0.12912355, -0.05208485],
       [-0.47161315,  0.21797577,  0.2816076 ],
       [ 0.10475428,  0.17853159,  0.26686533],
       [-0.38876944, -0.38162706,  0.1393081 ],
       [ 0.00369115, -0.43556786, -0.57414707]])

In [372]:
np.count_nonzero( x < 0.5)

1

In [374]:
np.sum(X < 6, axis=1)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [375]:
a = np.array([1,5,7,5,8])

In [378]:
np.all(a == 9)

False

In [379]:
summer = (np.arange(365) - 172 < 90) & (np.arange(365) - 172 > 0)
summer

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [381]:
np.random.RandomState(40)

RandomState(MT19937) at 0x271FFCCC340